### ISSUE TITLE
Use of functions deprecated in Kirby v4

### ISSUE THREAD

**Issue by mkasu** [thathoff/kirby-git-content#102]
Hi, I updated one of my websites to Kirby 4 and get this error when saving files, presumingly caused by git-content:

> The internal $model->contentFileDirectory() method has been deprecated. Please let us know via a GitHub issue if you need this method and tell us your use case.

**Comment by thathoff** [comment]
Thank you. Please use the kirby-4 branch (if you use composer use `dev-kirby-4` as a dependency).

**Comment by mkasu** [comment]
Thanks! Sorry for slow response. I can confirm the 5.2.0 update works well on my setup with Kirby 4.

**Comment by antiantivirus** [comment]
I have installed 5.2.0 and this error is still appearing for me. Running latest version of kirby 4.2.0

**Comment by thathoff** [comment]
Are you sure the newest release is used as I cannot reproduce it locally.
