### ISSUE TITLE
Doesnt recognize submodule?

### ISSUE THREAD

**Issue by syropian** [thathoff/kirby-git-content#40]
When I try and do a manual push or pull through the panel it says `"/home/forge/mysite.com/content" is not a git repository`, when in fact it's a submodule in the main repository. Any ideas why it thinks it's not?

**Comment by Pascalmh** [comment]
The content-Folder itself has to be a git repository.

See the Installation instrutions: https://github.com/blankogmbh/kirby-git-commit-and-push-content#create-a-new-git-repository-for-your-content

**Comment by syropian** [comment]
@Pascalmh I'm a little confused, is a submodule not considered a git repo? I can `cd` into it and manually push/pull. 

> Why would you want your content folder to be a submodule?

I just figured that's the most idiomatic way to have a "repo within a repo", but I'm no expert on them, and frankly was my first time using them.

**Comment by syropian** [comment]
Just an update: I switched the content folder to be a regular git repository. Pushing and pulling gives me success messages but it's not actually doing either. No commits have been made to the content repo, and pulling doesn't update anything.

**Comment by thathoff** [comment]
Hi @syropian, im currently taking over the maintenance of this plugin. This issue is quite old so I’ll close it. If you still have this issue feel free to open it again.
