### ISSUE TITLE
Authentication failed for git 

### ISSUE THREAD

**Issue by hamidasgarian** [thathoff/kirby-git-content#41]
my project coned fine by command:
git clone http://root@local-ip/root/project.git

but when i want to push it i get this error:
fatal: Authentication failed for 'http://root@local-ip/root/project.git/'
(i type correct password for user root and ssh root@local-ip work fine!)

my git config inside in cloned project its:
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = http://root@local-ip/root/project.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master

please someone with git knowledge help me

**Comment by thathoff** [comment]
Hi @hamidasgarian, im currently taking over the maintenance of this plugin. This issue is quite old so I’ll close it. If you still have this issue feel free to open it again.
