### ISSUE TITLE
Commits are not pushed to the remote with the default value of  `gcapc-branch`

### ISSUE THREAD

**Issue by shimikano** [thathoff/kirby-git-content#43]
Hello

I noticed that with the default value of `gcapc-branch` ([the empty string](https://github.com/blankogmbh/kirby-git-commit-and-push-content#gcapc-branch)), commits are not actually pushed to the remote, since, as it seems, the [resulting git call](https://github.com/kbjr/Git.php/blob/0.2.0/Git.php#L569) is

```
git push --tags origin
```

This does _not_ push the commits on the current branch (using git 2.11.0 here).

Can you confirm this behavior?

While this can be fixed by setting `gcapc-branch` explicitly, at least the documentation is misleading ("defaults to currently checked out branch").

A fix to consider would be calling 

```
$this->getRepo()->run("push origin $branch");
```

instead of 

```
$this->getRepo()->push('origin', $branch);
```

to avoid the `--tags` option.

What do you think?

Thank you.

**Comment by Pascalmh** [comment]
Did you do the [Installation step](https://github.com/blankogmbh/kirby-git-commit-and-push-content#installation) where you push the content repo? This should setup the tracking branch so you do not need to tell git every time you push which branch you want to push to.

The [--tags](https://git-scm.com/docs/git-push#git-push---tags) options pushes the local tags as well, there is no need to remove it (it won't fix the issue).

**Comment by shimikano** [comment]
Thanks a lot for getting back!

So, let's say I have a local commit:
```
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
```
The tracking branch seems to have been set before (`origin/master` appears in blue):
```
$ git branch -vv
* master 08b7c68 [origin/master: ahead 1] Testing...
```

And also:
```
$ git remote show origin
* remote origin
  [...]
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (fast-forwardable)
```

If I use the command from above, the commit is not pushed:
```
$ git push --tags origin
Everything up-to-date
```

What am I doing wrong?

**Comment by thathoff** [comment]
Hi @shimikano, im currently taking over the maintenance of this plugin. This issue is quite old so I’ll close it. If you still have this issue feel free to open it again.
