### ISSUE TITLE
Update readme.md to remove `site/plugins` pre-instruction

### ISSUE THREAD

**Issue by jh4mit** [thathoff/kirby-git-content#54]
readme.md instructs to go to site/plugins and then use git clone. This results in module being cloned into /site/plugins/site/plugins .

**Comment by thathoff** [comment]
Hmm, there seems to be no information in the readme about cloning the plugin into site/plugin. But even if you do it clones into the folder `kirby-git-content`

```
$ cd site/plugins
$ git clone git@github.com:thathoff/kirby-git-content.git
Cloning into 'kirby-git-content'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 430 (delta 19), reused 35 (delta 12), pack-reused 385
Receiving objects: 100% (430/430), 86.61 KiB | 943.00 KiB/s, done.
Resolving deltas: 100% (232/232), done.
$ ls -a1
.
..
kirby-git-content
$
```

If this issue still exists please open it again. Thanks!
