### ISSUE TITLE
Describe how to install manually inside Kirby’s plugin directory

### ISSUE THREAD

**Issue by frankgerhardt** [thathoff/kirby-git-content#55]
In [index.php](https://github.com/blankogmbh/kirby-git-commit-and-push-content/blob/master/index.php) I found this comment:

```php
<?php
// Support manual installation inside kirby’s plugin directory
require_once __DIR__ . '/vendor/autoload.php';
```

I can't get the composer way to work with my webhoster and wonder how can I install the plugin manually? Which files do I have to copy where?

**Comment by thathoff** [comment]
What you can do try to do it manually is to download the Plugin, run `composer install` inside the plugin folder. Afterwards you need to upload everything into the `site/plugins` directory.

I haven’t tested it yet but this is basically how it should work. If you have any issues feel free to comment here.

**Comment by thathoff** [comment]
It’s in the README https://github.com/thathoff/kirby-git-content#download-and-configure-the-plugin, maybe #62 will also make this work better.

If it’s still an issue feel free to open the issue again!
