### ISSUE TITLE
Unable to update git: fatal: empty ident name (for <my@email.com>) not allowed

### ISSUE THREAD

**Issue by moevbiz** [thathoff/kirby-git-content#57]
Whenever I try saving content from the panel, i get the following error message:

```
The form could not be saved
Exception: undefined
Unable to update git: fatal: empty ident name (for <bruno.mokross@gmail.com>) not allowed
``` 

my credentials are definitely set—
``` 
% git config --list
> user.name=my name
> user.email=my@email.com
```

I tested multiple times, following the steps in the README.md. 
I have an SSH key set and pushing changes from the terminal works just fine.

config.php looks like this: 
```
return [
  'blankogmbh' => [
    'gcapc' => [
      'commit' => true,
      'push' => true,
      'displayErrors' => true,
      'gitBin' => '/usr/bin/git'
    ],
  ],
];
``` 

I am using Laravel Valet, PHP 7.4 and MacOS Catalina

Is there anything super obvious I am doing wrong?

**Comment by thathoff** [comment]
Hi, it seems your Kirby User does not have a name. The plugin uses your Kirby user’s name and email address to commit.

**Comment by moevbiz** [comment]
ahhhhh, that did the trick. I'm now running into this issue… -> https://github.com/blankogmbh/kirby-git-commit-and-push-content/issues/53#issuecomment-498645663 but I'm sure I'll figure it out somehow. Thanks for your reply!
