### ISSUE TITLE
Allow Prefix (or Suffix) for commit messages

### ISSUE THREAD

**Issue by JonasDoebertin** [thathoff/kirby-git-content#63]
Right now, we're using this plugin to push content changes to the master branches of a site, that also has some CI/CD pipelines defined and attached to that branch. So every commit the plugin makes and pushes triggers a building pipeline what right now is, frankly, really not necessary.

We could stop the pipelines from running by adding a tag link `[skip ci]` to the commit messages the plugin generates. So at the end of the day, we'd need the option to add some kind of prefix or suffix to the generated commit messages.

Since this is a special request and I don't know if your own usages of the plugin would benefit from this, would you still be open to accepting a PR for this?

**Comment by thathoff** [comment]
Hi, for sure! Maybe it’s a good idea to make all commit message configurable. For example with placeholders like :action: :item: :url: so the current pattern would be `:action:(:item:): :url:` and you can easily configure that to be like `:action:(:item:): :url:\n\n[skip ci]` for your use case.

What do you think?

**Comment by JonasDoebertin** [comment]
Sound very reasonable to me.

**Comment by JonasDoebertin** [comment]
I created PR #64 for this

**Comment by thathoff** [comment]
Thank you! I’ll have a look at it…
