### ISSUE TITLE
Commits don't include Kirby Panel user as author

### ISSUE THREAD

**Issue by levajsics** [thathoff/kirby-git-content#68]
Heya, I ran into an issue where the git commits didn't contain the Kirby Panel user's name and email address. Stirred the code a bit, and turns out `$this->kirby->user()` was null when declaring $user. Replacing `$user = $this->kirby->user();` with `$user = kirby()->user();` in KirbyGitHelper.php#L107 seemingly fixed this issue (on my Kirby 3.4.2 install at least). ✨ I'm way too amateur to see why the og line didn't work, as `$this->kirby` works nicely elsewhere in the code. Anyway, I guess this is a heads-up, idk if anyone else had this problem. 👀

https://github.com/thathoff/kirby-git-content/blob/acb659330d5e2531b4e3063d09aec342f82f5259/src/KirbyGitHelper.php#L107

**Comment by thathoff** [comment]
Maybe the change has not been triggered by a Kirby user? Eg. if you create content with code and no authorised user? Because here it works perfectly. But I will have a look into it the next days.
