### ISSUE TITLE
commitMessage option name is wrong

### ISSUE THREAD

**Issue by lumpysimon** [thathoff/kirby-git-content#75]
In the readme, it says that the option to set the commit message is called `commitMessageTemplate`, but it is actually called `commitMessage`.

See line 27 of `KirbyGitHelper.php`:

`$this->commitMessageTemplate = option('thathoff.git-content.commitMessage', ':action:(:item:): :url:');`

**Comment by lumpysimon** [comment]
Fantastic plugin by the way, thank you 👍 💯

**Comment by thathoff** [comment]
Thank you. That’s right. I'll publish an update in the next weeks and fix the README.

**Comment by lumpysimon** [comment]
Thanks :)
