### ISSUE TITLE
plugin doesn't load with kirby 3.5.6

### ISSUE THREAD

**Issue by milovincent** [thathoff/kirby-git-content#79]
attempted to upgrade our site to kirby 3.5.6 (from 3.5.2) and am running into this error with this plugin:
![image](https://user-images.githubusercontent.com/4642401/123171422-cb184a80-d449-11eb-850c-8aebe0d5b944.png)
it's been very useful so we'd hate to lose it

**Comment by thathoff** [comment]
We’re running the current version (4.1.0) of this plugin with Kirby 3.5.6 just fine on multiple sites.

How did you install the plugin? Via Composer? Does Kirby work, when you disable the plugin?

**Comment by milovincent** [comment]
disabling the plugin via removing it works, yeah, but as it is, it's disabled in the config.php and still throwing that error.

**Comment by milovincent** [comment]
i believe it's installed with composer

**Comment by thathoff** [comment]
When you just disable the plugin it will still be loaded. So that’s an expected behaviour.

I have not found any way to reproduce this issue. Can you provide an example project where this happens?

**Comment by milovincent** [comment]
it'll be without content. that ok?

**Comment by milovincent** [comment]
ah, it's definitely kirby. i'll remove this issue.

**Comment by milovincent** [comment]
yuuup, fixed. needed to update with composer. problem solved!

**Comment by thathoff** [comment]
Thanks for the update.
