### ISSUE TITLE
Is it normal to end up with all sorts of uncommitted `.lock` file deletes?

### ISSUE THREAD

**Issue by shawninder** [thathoff/kirby-git-content#80]
When I modify a page in the panel a click save, the changes are correctly pushed to the content repo, but I don't end up with completely clean repo locally: there are changes not staged for commit. For example, this is what I have now after modifying my `sample-page`:
```sh
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    2_sample-page/.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

Is this normal? Can I ignore this? Or should I be worried that this dirty repo might prevent a commit from going through somewhere down the line?

Not too sure what to think…

**Comment by shawninder** [comment]
In fact, is it normal to have any lock file in the repo?

Should I perhaps manually remove all lock files from the repo and try again to see if things run better?

**Comment by thathoff** [comment]
Hi, I would recommend to add .lock files to .gitignore of your content repo. We should definitely add this to the README.

You can run `find . -name .lock -exec rm {}\ ;` in your repo. Then manually commit changes and add `.lock` to your `.gitignore` file.

**Comment by thathoff** [comment]
I’ve created a new issue for adding the information to the README: #81
