### ISSUE TITLE
Working locally but not on server

### ISSUE THREAD

**Issue by igregson** [thathoff/kirby-git-content#93]
Locally the plugin works as expected. 

On the server, it does not seem to be installed (but it is). The "Git Content" item in the dropdown menu is not there. I have `displayErrors` set to `true`. 

Any troubleshooting tips?

**Comment by thathoff** [comment]
Which version of Kirby and the plugin are you running on production? Do you have any errors on the console?

**Comment by igregson** [comment]
Kirby: 3.7.5
Plugin: 5.0.1

No, no error in the console.

**Comment by igregson** [comment]
I have two kirby config files, one base/default one and then one domain-specific one. I know that Kirby is recognizing the domain-specific one. In the base/default one I have the following (to turn off the plugin locally):

```php
'thathoff' => [
   'git-content' => [
      'disable' => true,
   ],
],
```

And then in my domain-specific config I have the following: 

```php
'thathoff' => [
   'git-content' => [
      'commit' => true,
      'push' => true,
      'displayErrors' => true,
   ],
],
```
