### ISSUE TITLE
error: unknown option `end-of-options'

### ISSUE THREAD

**Issue by graphichavoc** [thathoff/kirby-git-content#96]
I've installed Git Content on a server with git version 2.37.4. At the pull URL (<domain>/git-content/pull), I receive the following error, which I've never encountered before:

```
{"status":"error","message":"error: unknown option `end-of-options'\nusage: git fetch [<options>] [<repository> [<refspec>...]]\n   or: git fetch [<options>] <group>\n   or: git fetch --multiple [<options>] [(<repository> | <group>)...]\n   or: git fetch --all [<options>]\n\n    -v, --verbose         be more verbose\n    -q, --quiet           be more quiet\n    --all                 fetch from all remotes\n    -a, --append          append to .git\/FETCH_HEAD instead of overwriting\n    --upload-pack <path>  path to upload pack on remote end\n    -f, --force           force overwrite of local branch\n    -m, --multiple        fetch from multiple remotes\n    -t, --tags            fetch all tags and associated objects\n    -n                    do not fetch all tags (--no-tags)\n    -p, --prune           prune remote-tracking branches no longer on remote\n    --recurse-submodules[=<on-demand>]\n                          control recursive fetching of submodules\n    --dry-run             dry run\n    -k, --keep            keep downloaded pack\n    -u, --update-head-ok  allow updating of HEAD ref\n    --progress            force progress reporting\n    --depth <depth>       deepen history of shallow clone\n    --unshallow           convert to a complete repository"}
```

Any suggestions on how to fix?

My config block reads as follows:

```
'thathoff' => [
    'git-content' => [
      'path' => realpath(__DIR__ . '/../../'),
      'displayErrors' => false,
      'push'=> true,
    ],
  ]
```

**Comment by thathoff** [comment]
Hi, are you sure php is using the right git version? The `--end-of-options` option is [available since git 2.24](https://github.blog/2019-11-03-highlights-from-git-2-24/#tidbits).

**Comment by thathoff** [comment]
Any updates on this @graphichavoc?

**Comment by graphichavoc** [comment]
Hi @thathoff, I have found that I need to use Git Content version 4.1.0 with Kirby 3.8.2 in order to receive a success message. That is the best solution I have come up with for now.

**Comment by thathoff** [comment]
Thats quite strange: The part that does the endpoints did not change between the two versions. If you have any information which might give us a clue what’s happening here, that would be great.

**Comment by thathoff** [comment]
I’ll close this issue for now. If this error happens again and you can provide some more information feel free to open this issue again! :)

**Comment by graphichavoc** [comment]
Hi there, I ran into this exact issue again on a different project and server. Downgrading to 4.1.0 solved it again. Is there anything I can do to help you narrow down the causes? Any diagnostics you would recommend?

**Comment by thathoff** [comment]
Can you please check with git version php is using? Eg. by placing a script with this content on your server

```php
<?php system('git -v'); ?>
```

**Comment by graphichavoc** [comment]
This server is running git 1.8.3.1, so too low for the plugin, I see. That explains it. Thank you.

**Comment by thathoff** [comment]
You’re welcome and thank you for the feedback!
