### ISSUE TITLE
'KirbyGitHelper::$git is deprecated' error on saving 

### ISSUE THREAD

**Issue by CHE1RON** [thathoff/kirby-git-content#98]
When saving, I get this `Exception`:

```text
Unable to update git: Creation of dynamic property Thathoff\GitContent\KirbyGitHelper::$git is deprecated.
```

See here:

![image](https://github.com/thathoff/kirby-git-content/assets/122524301/52e7d680-bfb0-4342-bb4a-0c18a703c841)

PHP: v8.2.6

**Comment by thathoff** [comment]
Thank you, that’s probably easy to fix. It should be possible to run this with PHP 8.2 when disabling deprecation notices in php be setting `error_reporting = E_ALL & ~E_DEPRECATED` in `php.ini`

**Comment by thathoff** [comment]
Sure, sorry, you’re absolutely right ;) What i tried to say is that the real fix is quite easy but in the meantime you can go with the mentioned hotfix to prevent this error from showing up.

**Comment by CHE1RON** [comment]
Ah, I get it - maybe I find some time to examine it, but in any case I appreciate your effort with this plugin, which has already proven quite helpful!

**Comment by CHE1RON** [comment]
Thanks @thathoff !

**Comment by thathoff** [comment]
We have not made a new release yet which fixes the problem. If you install via composer try to use the version from master by requiring `dev-master` then it should work. Hopefully I’ll be able to create a new release in the next days.

**Comment by ericderid** [comment]
Ok thanks for the quick reply!

**Comment by CHE1RON** [comment]
Any particular reason not releasing v5.0.2 🤔

**Comment by thathoff** [comment]
Yes, time ;) But i’ve just released the new version 🥳

**Comment by CHE1RON** [comment]
🤩 now THAT is good news, fine Sir!
